# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = '''
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](cyan)$fill
[â”‚ ](cyan)$os$username$hostname $directory $status
[â””â”€](cyan)$character
'''
right_format = '''
$git_branch$git_status$nodejs$bun$rust$golang$python$cmd_duration$jobs
'''

[fill]
symbol = 'â”€'
style = 'cyan'

[character]
success_symbol = '[â‹Š>](cyan)'
error_symbol = '[â‹Š>](bold red)'

[username]
style_user = 'cyan'
style_root = 'red'
format = '[$user]($style)'
disabled = false
show_always = true

[directory]
truncation_symbol = 'â€¦/'
format = '\[[$path](green)\]'
repo_root_style = 'green bold'
before_repo_root_style = 'green'
repo_root_format = '[îœ‚](green) [$repo_root]($repo_root_style)[$path](green)'
truncate_to_repo = true
fish_style_pwd_dir_length = 1
home_symbol = "~"

[jobs]
format = "[$symbol$number](bold green) "
symbol = 'î©± '
number_threshold = 2
symbol_threshold = 1

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
"repos" = "î—»"

[cmd_duration]
min_time = 1
format = 'took [$duration](bold yellow) '

[git_branch]
symbol = 'îœ¥ '
format = '[$symbol$branch(:$remote_branch)](purple bold) '

[git_status]
format = "$ahead_behind$stashed$conflicted$deleted$renamed$modified$untracked$staged"
conflicted = '[C](red bold) '
ahead = '[â‡¡${count}](green) '
behind = '[â‡£${count}](yellow) '
diverged = '[â‡•â‡¡${ahead_count}](green)[â‡£${behind_count}](yellow) '
up_to_date = '[âœ“](green bold) '
untracked = '[?](yellow bold) '
stashed = '[î¬©](blue bold) '
modified = '[âœ—](red bold) '
staged = '[++\($count\)](green) '
renamed = "[ó°™](cyan) "
deleted = "[îª](red) "

[rust]
symbol = "îš‹ "
format = '[$symbol$version](red bold) '

[golang]
symbol = "î˜§ "
format = '[$symbol$version](bold cyan) '

[nodejs]
format = '[$symbol$version$engines_version]($style) '
symbol = "ó°™ "
style = "bold yellow"
not_capable_style = "bold red"

[python]
format = "[$symbol$pyenv_prefix($version )(($virtualenv) )]($style)"
symbol = 'îœ¼ '
pyenv_version_name = false
style = "yellow bold"
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']

[status]
style = 'bold red'
symbol = 'ï— '
format = '[\($symbol$common_meaning$signal_name$maybe_int $status\)]($style) '
disabled = false

[bun]
format = '[ğŸ” $version](bold green) '

[hostname]
ssh_only = true
format = '[@](green)[$hostname](purple)'
trim_at = '.local'
disabled = false

[os]
format = "$symbol"
style = "white"
disabled = false
[os.symbols]
Macos = "ï…¹ "

# [battery]
# full_symbol = 'ğŸ”‹ '
# charging_symbol = 'âš¡ï¸ '
# discharging_symbol = 'ğŸ’€ '
# [[battery.display]]
# threshold = 100
# style = 'bold red'
