# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = '''
$username$hostname \[$directory\] $character
'''
right_format = '''
$git_branch$git_status$rust$package$bun$cmd_duration
'''

[character]
success_symbol = '[â‹Š>](cyan)'
error_symbol = '[â‹Š>](bold red)'

[username]
style_user = 'cyan'
style_root = 'red'
format = '[$user]($style)'
disabled = false
show_always = true

[directory]
truncation_symbol = 'â€¦/'
format = '[$path](green)'
repo_root_style = 'green bold'
before_repo_root_style = 'green'
repo_root_format = '[îœ‚](green) [$repo_root]($repo_root_style)[$path](green)'
truncate_to_repo = true
fish_style_pwd_dir_length = 1
home_symbol = "~"

[cmd_duration]
min_time = 0
format = 'took [$duration](bold yellow)'

[git_branch]
symbol = 'îœ¥ '
format = '[$symbol$branch(:$remote_branch)](purple bold) '

[git_status]
format = "$up_to_date$modified$staged$ahead$behind$conflicted$untracked"
ahead = '[â‡¡${count}](green) '
diverged = '[â‡•â‡¡${ahead_count}](green)[â‡£${behind_count}](yellow) '
behind = '[â‡£${count}](yellow) '
conflicted = '[C](red bold) '
up_to_date = '[âœ“](green bold) '
stashed = 'î¬© '
modified = '[âœ—](red bold) '
staged = '[++\($count\)](green) '

[rust]
symbol = "îš‹ "
format = '[$symbol$version](red bold) '


[nodejs]
format = 'via [ğŸ¤– $version](bold green) '


[hostname]
ssh_only = true
format = '[@](green)[$hostname](purple)'
trim_at = '.local'
disabled = false

[bun]
format = '[ğŸ” $version](bold green) '

# [battery]
# full_symbol = 'ğŸ”‹ '
# charging_symbol = 'âš¡ï¸ '
# discharging_symbol = 'ğŸ’€ '
# [[battery.display]]
# threshold = 100
# style = 'bold red'